spring.application.name=wedding
spring.datasource.driver-class-name=org.postgresql.Driver
spring.autoconfigure.exclude=org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration,org.mybatis.spring.boot.autoconfigure.MybatisLanguageDriverAutoConfiguration
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# prod
server.port=${PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# local
#server.port=8080
#spring.datasource.url=jdbc:postgresql://ep-dark-cake-acx1idzf-pooler.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_NAO5DeEw2jvR --> ?? pwd





